import { useEffect, useState } from 'react';
export function ButtonEmailShare({ children , elevatorParams}) {
    const [emailUrl, setEmailUrl] = useState('');
    useEffect(() => {
        let baseUrl = "mailto:sales@fesiparts.com?subject=Custom Cab Size Consult&body=Hello, please advise pricing based on my preferences.%0D\n"
        
        for (const [key, value] of Object.entries(elevatorParams)) {
            baseUrl += key + ": " + value + "%0D";
        }
        baseUrl += "%0D%0DThank you!%0D%0D";
        baseUrl += "This email was generated by the F Elevator Configurator.";
        setEmailUrl(baseUrl);
    }
    , [elevatorParams]);


    return (
        <a className="btn btn-secondary"
            href={emailUrl}>
            {children}  &nbsp;
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className="bi bi-envelope" viewBox="0 0 16 16">
                <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1zm13 2.383-4.708 2.825L15 11.105zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741M1 11.105l4.708-2.897L1 5.383z" />
            </svg>
        </a>
    )
}